export const source = {
  html: `<p>Provider Search is a Carelon Behavioral Health (Carelon) online directory for locating providers. Provider Search offers you the ability to locate Carelon network providers and facilities throughout the country. The use of this provider directory does not provide authorization for benefits or services. Prior to beginning any care or program with a provider, you should contact Carelon Behavioral Health to obtain benefits and be notified of any requirements specific to your benefit plan where applicable. If you are unable to locate a network provider through our directory, please call the number on the back of your health insurance card for assistance in locating a network provider.</p>
           <p>Carelon Behavioral Health of California (Carelon of California) is a subsidiary of Carelon Behavioral Health. In order to search for a provider in the Carelon of California Mental Health or Substance Use Disorder or Mental Disorder (MHSUD) and/or Employee Assistance Program (EAP) networks, you have been directed to the Carelon Behavioral Health Provider Search site.</p>
           <p>Carelon makes every effort to maintain accurate and up-to-date information. However, changes can occur at any time. The practice locations at which the provider/facility will see members is self-reported and verified during the initial credentialing process and every three years, as required by applicable state law. Self-reported practice location changes are updated on the website at least weekly.</p>
           <p>To report possible inaccurate, incomplete, or misleading directory information, you may contact Carelon Behavioral Health by sending an email to <a href="mailto:prsfeedback@carelon.com">prsfeedback@carelon.com</a> or through the "Report Corrections" link within each individual provider's file. For practitioners participating with CAQH, updates are required to be made via CAQH for information to be visible within Carelon’s Provider directory by authorizing release of your individual profile information to Carelon Behavioral Health, reviewing and attesting to your information. Facilities and Provider Groups may also change or update their information by visiting the provider portal or by calling the National Provider Services Line at <a href="tel:800-397-1630">800-397-1630</a>, Monday through Friday, 8 a.m.-8 p.m. ET, while members may call the toll-free number on their member identification card.</p>
         
          <p>For consumers in Massachusetts, you may file complaints relating to Provider Directory inaccuracies or Provider network inadequacy to the Commonwealth's Division of Insurance. To do so, please visit <a href="https://www.mass.gov/how-to/filing-an-insurance-complaint">https://www.mass.gov/how-to/filing-an-insurance-complaint</a> and follow the instructions on how to submit online or by mail.</p>
          <p>Members are entitled to full and equal access to covered services, including members with disabilities as required under the Americans with Disabilities Act of 1990 and Section 504 of the Rehabilitation Act of 1973.</p>
          <p><strong>IMPORTANT:</strong> You can get an interpreter at no cost to talk to your doctor or health plan. To get an interpreter or to ask about written information in your language, first call the toll-free number on your member identification card.</p>
          <p>Carelon Behavioral Health of California, Inc. (Carelon of California) If you have an administrative question or inquiry regarding eligibility, benefit coverage or any other matter relating to the Carelon of California MHSUD or EAP benefit plans or if you believe you reasonably relied upon materially inaccurate, incomplete, or misleading directory information and wish to submit a complaint, you may telephone our Member Service Department at <a href="tel:800-228-1286">800-228-1286</a> or call the telephone number listed in your Combined Evidence of Coverage and Disclosure Form. Our Member Services staff will work with you to resolve the matter.</p>
         <p><strong>IMPORTANT:</strong> You can get an interpreter at no cost to talk to your doctor or health plan. To get an interpreter or to ask about written information in your language, first call our Member Services Department at <a href="tel:800-228-1286">800-228-1286</a>. Someone who speaks your language can help you. If you need more help, you are encouraged to contact the Department of Managed Health Care, which protects consumers, by telephone at its toll-free number <a href="tel:888-466-2219">888-466-2219</a>, or at a TDD number for the hearing and speech impaired at <a href="tel:877-688-9891">877-688-9891</a>, or online at <a href="http://www.dmhc.ca.gov">http://www.dmhc.ca.gov</a>.</p>
         <p>Members are entitled to full and equal access to covered services, including members with disabilities as required under the Americans with Disabilities Act of 1990 and Section 504 of the Rehabilitation Act of 1973.</p>`,
};
