export const source = {
  html: `<h1>Employee Assistance Program EAP Participant Statement of Understanding</h1> 
      <p><b>To Our EAP Participants:</b></p> 
      <p>Carelon Behavioral Health, Inc. is pleased that you have decided to use your Employee Assistance Program ("EAP"). The EAP is a voluntary service available to eligible employees and family members. There are several things we want you to know before we begin discussing your reason for contacting the EAP.</p> 
      <p>Personal problems are sometimes very difficult to talk about. That is why confidentiality is extremely important to us. We take every precaution in protecting the confidentiality of your visit with us and we hope that you will do the same. A written and electronic record (date, time, nature of meeting) of your contacts with the EAP will be maintained in a secure manner. Access to the record will not be given to anyone outside of the EAP, except as required by law or as described below. Aggregate utilization data may be provided to your employer, this aggregate data will not contain any information that identifies you. To access your file, contact Carelon Behavioral Health, Inc.</p>
      <p>This provides an opportunity for you to discuss personal problems with us. We will help you with an assessment of your personal problems and then develop a plan of action with you. The plan of action may include a referral to an appropriate resource to help you resolve your problems. After the referral is made, we will follow up to be sure the referral is satisfactory. In the event that there is no referral, we will still develop an action plan with you.
      Lawful release of records is permitted under the following conditions: if we learn about child, elder or disabled adult abuse or neglect, if you pose a threat of imminent danger to yourself or others, if we are required to present records to comply with a court order, to comply with other state and federal requirements, and if we learn about any emergency medical circumstances which require immediate medical attention.</p>
      <p>To the extent possible, we want to ensure the counselor that you will be meeting with is a person with whom you are comfortable. For example, some people have a preference for a counselor of a particular gender, sexual orientation, ethnicity, or religion. If this is a concern, Carelon Behavioral Health, Inc. would like to give you the opportunity to let us know so that we may attempt to arrange a referral to a counselor that is appropriate for you. Should you have any concerns or be dissatisfied with the EAP or your counselor, please contact Carelon Behavioral Health, Inc.</p>
      <p>There is no cost to you for any EAP services provided by Carelon Behavioral Health, Inc. The Employee Assistance Program does not, however, cover the costs of therapy or community resources/treatment services to which you may be referred. We attempt to maintain up-to-date information on your health insurance coverage so that we can refer you to providers covered by your plan. However, it is your responsibility to verify that your insurance will cover the cost of Employee Assistance Program EAP Participant Statement of Understanding such therapy or other treatment or resources.</p>
      `,
};
