export const source = {
  html: `<h1>Terms of use</h1> 
    <p>These Terms of Use (“Terms”) apply to those mobile applications and websites that we operate (each an “Application”) and that contain a link to these Terms. By using our Applications you are agreeing to the following:</p> 
    <p><b>Use of this application</b></p> 
    <p>The contents of this Application – whether the content is ours or is licensed to us by a third party -- are protected by copyright. We authorize you to view and download material on this Application solely for your own use. You may not sell or modify the material or otherwise use it for any commercial purpose.</p> 
    <p>You will not use this Application in violation of any laws, including the fraud and abuse or anti-kickback provisions of the federal Medicare and Medicaid laws.</p> 
    <p>You will not, and will not permit anyone else to: (1) modify, adapt, alter, translate, or create derivative works of this Application; (2) use or merge this Application, or any component or element of this Application, with other software, databases, or services not provided by us; (3) sublicense, distribute, sell, or otherwise transfer the Application to any other party; (4) use the Application as a service bureau, or lease, rent, or loan this Application to any third party; (5) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code or structure of this Application; (6) interfere in any manner with the operation of this Application; (7) circumvent, or attempt to circumvent, any electronic protection measures in place to regulate or control access to this Application; (8) create a database by systematically downloading and storing this Application; (9) use any robot, spider, site search/retrieval application, or other manual or automatic device to retrieve, index, "scrape," "data mine", or in any way gather information from this Application, or reproduce, or circumvent the navigational structure, or presentation of this Application.</p> 
    <p><b>Use of information and resources</b></p> 
    <p>We make this Application available for the purpose of providing information to consumers about our products and services. Nothing on this Application is intended to be a substitute for professional medical advice or for the care that patients receive from their physicians. Nothing in this Application is intended to be used for medical diagnosis or treatment. You should not disregard medical advice, or delay seeking medical advice, because of something you read on this Application.</p> 
    <p>We are not responsible for information provided by health information content providers, third-party sites linked to, or framed by the Application, and we do not make any representations regarding the content, accuracy, or timeliness of any of such information.</p> 
    <p><b>Anonymous IP address</b></p> 
    <p>We consider the protection of your health and personal information an important responsibility. Anonymous IP addresses are a technique known to be used by cyber criminals. Because of this, we do not allow access to the secure member portal for users coming to the site with anonymous IP addresses. A blocked or anonymous IP address could be caused by your network, personal VPN, or other reasons. As a result, you may want to try to access the portal using a method that doesn’t block your IP address or, if you are using a work computer, talk to your employer about how their network displays IP addresses.</p> 
    <p><b>Use of email and fax</b></p> 
    <p>We may provide email links to further facilitate communication between you and us. Information collected through email may be shared with our member services department, other associates, or third parties that perform services on our behalf. Unless otherwise noted, email through our website is not a completely secure and confidential means of communication. Non-encrypted email may be accessed and viewed by other Internet users without your knowledge and permission while in transit to us.</p> 
    <p><b>Linking to other application</b></p> 
    <p>From time to time we will provide links to websites not owned or controlled by us. We do this because we think the information might be of interest or use to you. A link to a third-party website does not constitute or imply endorsement by us. We cannot guarantee the quality or accuracy of information presented on third-party websites. While we do our best to ensure your privacy, we cannot be responsible for the privacy practices of third-party websites. We encourage you to review the privacy practices of any website you visit.</p> 
    <p><b>Appropriateness of content</b></p> 
    <p>This Application is not intended to attract children under the age of 13. We do not collect personal information from any user that we know is under the age of 13. Some of the content on this Application may not be appropriate for children. Parents or guardians are solely responsible for providing supervision of minors’ use of this Application.</p> 
    <p><b>Digital millennium copyright act</b></p> 
    <p>We respect the intellectual property of others. If you believe that your copyrighted work has been copied in a way that constitutes copyright infringement and is accessible on or through this Application, you must provide the following information to us when providing notice of the claimed infringement:</p> 
    <ul> 
     <li>A physical or electronic signature of a person authorized to act on behalf of the copyright owner and identification of the copyrighted work that is infringed.<br> </li> 
     <li>Information reasonably sufficient to permit us to contact you, such as an address, telephone number, and/or email address.<br></li> 
     <li>A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or law.<br></li> 
     <li>A statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li> 
    </ul> 
    <p>The above information must be submitted in writing to us at 220 Virginia Avenue, Indianapolis, IN 46204, ATTENTION: LEGAL DEPARTMENT/DMCA COMPLAINT. This information should not be construed as legal advice. For further details on the information required for valid DMCA notifications, see 17 U.S.C. 512(c)(3).</p> 
    <p><b>No liability</b></p> 
    <p>No Liability. WE AND OUR LICENSORS AND SUPPLIERS (INCLUDING ALL PROVIDERS OF CONTENT FOR THIS APPLICATION) SHALL NOT BE LIABLE TO YOU, UNDER ANY CIRCUMSTANCES OR UNDER ANY THEORY OF LIABILITY OR INDEMNITY, FOR ANY DAMAGES OR PENALTIES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL INDIRECT, EXEMPLARY, PUNITIVE AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) IN CONNECTION WITH THE USE OR INABILITY TO USE THIS APPLICATION OR THE CONTENT, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. WE SHALL BE LIABLE TO YOU ONLY TO THE EXTENT OF ACTUAL DAMAGES INCURRED BY YOU. THE REMEDIES STATED FOR YOU IN THESE TERMS AND CONDITIONS ARE EXCLUSIVE AND ARE LIMITED TO THOSE EXPRESSLY PROVIDED FOR IN THESE TERMS AND CONDITIONS.
    We and our licensors and suppliers are not responsible for any claims you may have against any medical professionals, suppliers of products, or other persons, institutions, or entities identified in whole or in part through this Application. No Warranties.
   <br>THE APPLICATION AND ITS SERVICES, CONTENT AND INFORMATION ARE PROVIDED "AS IS." WE AND OUR LICENSORS AND SUPPLIERS DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, NONINFRINGEMENT OF THIRD PARTIES RIGHTS, OR FITNESS FOR A PARTICULAR PURPOSE.</p> 
    <p><b>Limitations</b></p> 
    <p>We are not licensed to sell products and services in all states. The descriptions of products and services contained in this Application may not contain all the terms, conditions, limitations, and exclusions that may be applicable. Before purchasing any health plan, you should read the contract or explanation of benefits that contains all exclusions and limitations on coverage.</p> 
    <p><b>Termination</b></p> 
    <p>We may terminate any users’ right to use this Application at any time. We reserve the right to block, delete, or stop the uploading of materials and communications that we find unacceptable for any reason. If your right to use this site ends, you shall make no further use of this site, or any information obtained from this site.</p> 
    <p><b>CHANGES TO THESE TERMS</b></p> 
    <p>We may revise, modify, or amend these Terms at any time. Any such revision, modification or amendment shall be effective immediately upon either posting it to the Application or otherwise notifying you. These terms were most recently updated November 1, 2016.</p> 
    <p><b>Miscellaneous</b></p> 
    <p>We make no claims that the content and information included at this Application is appropriate or may be downloaded outside of the United States. Access to the content and information included in this Application may not be legal by certain persons or in certain countries. If you access this Application from outside the United States, you do so at your own risk and are solely responsible for compliance with the laws of your jurisdiction and any other applicable laws.</p> 
    <p>These Terms shall be governed and construed in accordance with the laws of the State of Indiana without regard to the choice of law provisions of any jurisdiction. We may without notice to you assign our rights and duties under these Terms to any party at any time. Failure to enforce or insist on strict performance of any provision of these Terms shall not be construed as a waiver of any provision or right. You agree that any legal action or proceeding between us and you in any way related to these Terms shall be brought exclusively in a court of a competent jurisdiction sitting in Indianapolis, Indiana. Any cause of action or claim you may have against or involving us must be commenced within one year after the claim or cause of action arises. Neither the course of conduct between the parties nor trade practice shall modify the provisions of these Terms. The invalidity or unenforceability of any provision shall not in any way affect the validity or enforceability of the rest of these Terms. These Terms constitute the entire agreement between you and us regarding your use of this Application, and it supersedes all prior agreements, representations, proposals, and other communications with respect to this Application and its content.</p> 
    <p><b>Use of text</b></p> 
    <p>These Texting Terms and Conditions apply when you provide prior express consent to receive text messages from Carelon businesses, agents, contractors, or vendors ("us" or "we" or "our'). Text messaging from us may include one-time or recurring texts related to your benefits, programs, products, services, and tools, and/or general health information. At enrollment for recurring texting programs, we specify the frequency of texts and information on how to unsubscribe and seek assistance. In all programs, you may text “STOP” to stop messaging for that program and "HELP" for help. Text messages will be sent to your mobile number using an automatic dialing system. Message and Data rates may apply.</p> 
    <p>Participation is optional. You are electing to receive PHI via text which makes the data transmitted available to your phone carrier and potentially others. Anthem provides alternative means for communicating including phone. You understand you have these choices and have elected to opt-in for texting. Anthem does not require that you agree to receive texts for this purpose to receive treatment, payment, or for benefits enrollment and eligibility.</p> 
    <p>If you no longer want to receive text messages from us, the sole and exclusive remedy is to end enrollment in the specific texting program.</p> 
    <p>Under no circumstances will we be liable for any direct or indirect, incidental, consequential, special, exemplary, or punitive damages arising out of or in connection with use of text messaging whether or not we have been advised of the possibility of such damages.</p> 
    <p>We do not guarantee the successful delivery of text messages by your wireless provider. Messages sent by text may not be delivered if the mobile device is not in range of a transmission site, or if sufficient network capacity is not available at a particular time. Even within a coverage area, factors beyond the control of wireless carriers may interfere with message delivery, including the terrain, proximity to buildings, foliage, weather, and the recipient's equipment. We will not be liable for losses or damages arising from (a) non-delivery, delayed delivery, or misdirected delivery of a text message; (b) inaccurate or incomplete content in a text message; or (c) use or reliance on the content of any text message for any purpose.</p> 
    <p>Please notify us immediately if your mobile number changes. We are not liable for any communication or transmission of information by text which happens because you did not report that your mobile number changed. Password-protecting mobile device(s) and enabling encryption, if available, is recommended.</p> 
    <p>Text messages may include protected health information (PHI). Since text messaging is unencrypted, there is a risk that this PHI could be intercepted or viewed by third parties, including others who access your device. When you choose to receive text messages from us, you do so at your own risk. Once texted, your information may no longer be regulated under HIPAA’s Privacy Rule. © 2022</p> 
    </div><div></div></div>`,
};
