import { StyleSheet } from 'react-native';

import { appColors } from '../../../../src/config';
import { appFonts } from '../../context/appFonts';

const TITLE_WIDTH = '45%';
const VALUE_WIDTH = '55%';

export const crisisStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  cardContainer: {
    height: 'auto',
    borderColor: appColors.lighterGray,
    borderWidth: 1,
    marginVertical: 5,
  },
  label: {
    fontFamily: appFonts.semiBold,
    fontWeight: '600',
    fontSize: 16,
    width: TITLE_WIDTH,
    paddingLeft: 10,
    textAlign: 'left',
    textAlignVertical: 'center',
    color: appColors.white,
  },
  headerTitle: {
    width: VALUE_WIDTH,
  },
  cardStyle: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginTop: 15,
    alignItems: 'center',
  },
  headerTitlesView: {
    backgroundColor: appColors.lightPurple,
    flexDirection: 'row',
    borderTopLeftRadius: 6,
    borderTopRightRadius: 6,
    paddingVertical: 5,
    justifyContent: 'flex-start',
    alignContent: 'flex-start',
  },
  title: {
    fontSize: 20,
    color: appColors.darkGray,
    marginVertical: 12,
    fontWeight: '600',
    fontFamily: appFonts.medium,
    textAlignVertical: 'center',
  },
  titleCell: {
    fontSize: 16,
    flex: 1,
    color: appColors.lightPurple,
    fontWeight: '500',
    paddingVertical: 5,
    paddingLeft: 10,
    fontFamily: appFonts.medium,
  },
  prefixText: {
    fontSize: 16,
    color: appColors.darkGray,
    fontWeight: '400',
    paddingVertical: 5,
    textAlign: 'left',
    fontFamily: appFonts.regular,
  },
  cell: {
    fontSize: 16,
    flex: 1,
    color: appColors.lightPurple,
    fontWeight: '500',
    paddingVertical: 5,
    textAlign: 'left',
    fontFamily: appFonts.medium,
  },
  spaceToLinkCell: {
    fontSize: 16,
    flex: 1,
    color: appColors.lightPurple,
    fontWeight: '500',
    paddingTop: 5,
    textAlign: 'left',
    paddingLeft: 5,
    fontFamily: appFonts.medium,
  },
  coverageCell: {
    fontSize: 16,
    flex: 1,
    fontWeight: '400',
    color: appColors.darkGray,
    paddingVertical: 5,
    fontFamily: appFonts.regular,
  },
  coverageContainer: {
    width: VALUE_WIDTH,
    borderRightWidth: 1,
    borderRightColor: appColors.lighterGray,
    paddingBottom: 25,
    paddingHorizontal: 10,
  },
  hotlineContainer: {
    width: TITLE_WIDTH,
    borderRightWidth: 1,
    borderRightColor: appColors.lighterGray,
    paddingBottom: 25,
  },
  innerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  dotView: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: appColors.darkGray,
    alignSelf: 'flex-start',
    marginTop: 12,
  },
  coverageView: {
    width: '90%',
    flexDirection: 'row',
    paddingHorizontal: 10,
    flexWrap: 'wrap',
  },
  toolTipView: {
    width: '10%',
  },
  infoView: {
    paddingHorizontal: 5,
    justifyContent: 'center',
    paddingVertical: 7,
    alignContent: 'center',
  },
  tooltipDotView: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: appColors.darkGray,
    marginRight: 10,
    marginTop: 5,
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  tooltipText: {
    color: appColors.darkGray,
    fontSize: 16,
    fontWeight: 400,
    fontFamily: appFonts.regular,
  },
  popoverContainer: {
    position: 'absolute',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 6,
    maxWidth: 200,
    flexDirection: 'row',
    alignItems: 'center',
    borderColor: appColors.lightPurple,
    borderWidth: 2,
    backgroundColor: appColors.white,
  },
  notchContainer: {
    position: 'absolute',
    top: '50%',
    right: 0,
    width: 0,
    height: 0,
    overflow: 'visible', // Ensure the notch is visible
  },
  notch: {
    width: 0,
    height: 0,
    borderTopWidth: 10,
    borderTopColor: appColors.transparent,
    borderBottomWidth: 10,
    borderBottomColor: appColors.transparent,
    borderLeftWidth: 10,
    borderLeftColor: appColors.white,
  },
});
