export interface AppColors {
  backgroundGray: string;
  black: string;
  blackOpacity90: string;
  blue: string;
  cyan: string;
  dark: string;
  darkGray: string;
  darkPurple: string;
  darkRed: string;
  darker: string;
  error: string;
  gray: string;
  green: string;
  light: string;
  lightDarkGray: string;
  lightGray: string;
  lightModalGray: string;
  lightPurple: string;
  lightRed: string;
  lightShadedGray: string;
  lighter: string;
  lighterGray: string;
  lighterPurple: string;
  lineGray: string;
  mediumDarkGray: string;
  mediumGray: string;
  mediumLightGray: string;
  mediumLightPurple: string;
  neutralGray: string;
  orange: string;
  overlay: string;
  paleCyan: string;
  paleGray: string;
  paleLavender: string;
  palePurple: string;
  paleRed: string;
  paleTurquoise: string;
  paleYellow: string;
  placeholderText: string;
  purple: string;
  purpleBgColor: string;
  red: string;
  requiredRed: string;
  shadowBlack: string;
  shadowColor: string;
  shadowGrey: string;
  thickGray: string;
  thickerGray: string;
  thinGray: string;
  thinPurple: string;
  transparent: string;
  turquoise: string;
  veryDarkGray: string;
  veryLightGray: string;
  veryPaleGray: string;
  white: string;
}

export const appColors: AppColors = {
  white: '#FFFFFF',
  light: '#DAE1E7',
  lighter: '#F3F3F3',
  dark: '#444444',
  darker: '#222222',
  black: '#000000',
  red: '#FF0000',
  orange: '#FFA500',
  green: '#43a31f',
  purple: '#5009B5',
  paleLavender: '#EEE4FF',
  darkPurple: '#2B1B49',
  lightPurple: '#794CFF',
  lighterPurple: '#bbafe9',
  palePurple: '#EBE4FF',
  turquoise: '#00BBBA',
  paleTurquoise: '#D9F5F5',
  cyan: '#44B8F3',
  paleCyan: '#e1edff',
  gray: '#666',
  darkGray: '#231E33',
  backgroundGray: '#FAFAFA',
  mediumDarkGray: '#2d2d2d',
  mediumGray: '#333333',
  mediumLightGray: '#7b7b7b',
  lightGray: '#CCCCCC',
  lighterGray: '#EEEEEE',
  paleGray: '#F5F5F5',
  lightRed: '#d20a3c',
  lightModalGray: '#00000080',
  lightDarkGray: '#666666',
  thickGray: '#0000004C',
  blackOpacity90: '#00000090',
  lightShadedGray: '#DADADA',
  shadowColor: '#000',
  thickerGray: '#949494',
  darkRed: '#E8373A',
  mediumLightPurple: '#794CFF33',
  purpleBgColor: '#E0DAF966',
  lineGray: '#C4C4C4',
  placeholderText: '#999999',
  error: '#E8373A',
  thinGray: '#F8FAFC',
  thinPurple: '#794CFF20',
  paleRed: '#E85C5E',
  paleYellow: '#FDE6B9',
  overlay: '#00000080',
  transparent: 'transparent',
  shadowBlack: '#0000001A',
  veryDarkGray: '#1C1C1C',
  veryLightGray: '#F6F6F6',
  neutralGray: '#838590',
  veryPaleGray: '#E5E8EA',
  blue: '#007AFF',
  requiredRed: '#DC4A3F',
  shadowGrey: '#D3D3D3',
};
