export const APP_CONTENT = {
  FOOTER: {
    TERMS: 'Terms of Use',
    PRIVACY: 'Privacy Policy',
    COPYRIGHT: '© 2024 Carelon.',
    COPYRIGHT_MODEL_TITLE: 'Carelon Provider Search',
    COPYRIGHT_MODEL_DESCRIPTION:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.                                                            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum  \n  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolm.                                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.                                                            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum  \n  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
    COPYRIGHTS_OK_BUTTON: 'OK',
  },
  HEADER: {
    TITLE: 'Carelon',
    SUBTITLE: 'Wellbeing resources you can trust.',
  },
  SPLASH: {
    TITLE: 'Carelon',
    TEXT: 'Wellbeing resources you can trust.',
    BUTTON_TEXT: 'Create Account',
    BUTTON_SUBTEXT: 'Have an account?',
    BUTTON_SUBTEXT_NAV: 'Log In',
  },
  LOGIN: {
    TITLE: 'Log In',
    SUBTITLE: 'Please use the email and password used for registering your account to Login',
    EMAIL: 'Email',
    SECRET: 'Password',
    BUTTON_TEXT: 'Log In',
    BUTTON_SUBTEXT: 'Forgot Password?',
    BUTTON_SUBTEXT_NAV: 'Reset Password',
    REMEMBER_ME_TEXT: 'Remember Me',
    REMEMBER_FLAG: 'rememberFlag',
    BACKEND_ERROR_VALIDATION: 'User not found/ password incorrect',
    BUILD_NUMBER: 'Build No: ',
  },
  CREATE_ACCOUNT: {
    TITLE: 'Create Account',
    SUBTITLE: 'Please create an account with a valid email account',
    NAME: 'Name',
    PLACEHOLDER: 'Email',
    BUTTON_TEXT: 'Send Email',
    BUTTON_SUBTEXT: 'Have an account?',
    BUTTON_SUBTEXT_NAV: 'Log In',
    EMAIL_ERROR: 'Invalid email address',
    USER_EXIST_ERROR: 'User already exists',
    USER_NOT_FOUND: 'User not found',
    EMAIL_ADDRESS: 'Email Address',
    VERIFY_OTP_LIMIT_ERROR: 'User exceeded the validation limit. Request resend OTP before validating again.',
    VERIFY_OTP_ACCOUNT_LOCK_ERROR: 'User exceeded the validation limit. Sorry account will be blocked!!',
  },
  VERIFY_CODE: {
    TITLE: 'Verification',
    SUBTITLE: 'Please login to your email account to retrieve secure code sent',
    TITLE_CODE: 'Code',
    BUTTON_TEXT: 'Verify Code',
    BUTTON_SUBTEXT: "Didn't receive an email?",
    BUTTON_SUBTEXT_NAV: 'Resend Email',
    ERROR_TEXT: 'Invalid code',
  },
  COMPLETE_REGISTRATION: {
    TITLE: 'Register (Step 1 of 2)',
    SUBTITLE: 'Please register your account with your details and setting a password',
    BUTTON_TEXT: 'Continue',
    TITLE_FIRST_NAME: 'First Name',
    TITLE_LAST_NAME: 'Last Name',
    ERROR_FIRST_NAME: 'Enter valid first name',
    ERROR_LAST_NAME: 'Enter valid last name',
    TITLE_SECRET: 'Password',
    ERROR_SECRET:
      'Must be at least 8 characters long and have at least 1 lowercase, 1 uppercase, 1 number, and 1 of special characters $!@*?|',
    TITLE_REENTER_SECRET: 'Re-enter Password',
    ERROR_REENTER_SECRET: 'Password does not match',
    SECRET_EMPTY_VALIDATION: 'Invalid password',
    ACCEPT_TERMS_CONDITIONS: 'I accept the Terms & Conditions',
    PUSH_NOTIFICATION_CONDITIONS: 'Allow Push Notification',
    STEP2: {
      TITLE: 'Register (Step 2 of 2)',
      BUTTON_TEXT: 'Login',
    },
  },
  RESET_SECRET: {
    TITLE: 'Reset Password',
    SUBTITLE: 'Please provide email userid for registering your account',
    SUBTITLE1: 'Please provide email used for registering your account.',
    STEP2: {
      SUBTITLE: 'Your account has been updated with your new password',
      TITLE: 'Password Changed',
    },
    RESET_SECRET_SUBTITLE: 'Please enter and re-confirm a new password.',
    BUTTON_TEXT: 'Update Password',
    RETURN_LOGIN: 'Return to Log In',
    LOGIN_DESC: 'Please confirm your email account to reset your password.',
  },
  MENU: {
    TITLE: 'Menu',
    SUBTITLE: 'Explore more',
    PUSH_NOTIFICATIONS: 'Push Notifications',
    RESET_SECRET: 'Reset Password',
    PUSH_NOTIFICATIONS_RECEIVE: 'You will receive notifications.',
    PUSH_NOTIFICATIONS_NOT_RECEIVE: 'You will not receive notifications.',
    PUSH_NOTIFICATIONS_ON: 'On',
    PUSH_NOTIFICATIONS_OFF: 'Off',
    CONTACT_US_TEXT:
      'If you require emergency services, please call 911. If you care experiencing a mental health crisis, call 988. For immediate EAP support, contact',
    CONTACT_US_PHONE_NO: '1-888-445-4436',
    MANAGE_ACCOUNT: 'Manage Account',
    DELETE_ACCOUNT: 'Delete Account',
    DELETE_ACCOUNT_DESC:
      'This will remove access to the Carelon application and remove all information saved information.',
    DELETE_INPUT_LABEL: 'To confirm, type "DELETE"',
    NOTIFICATIONS_OFF_ALERT: 'You have turned off notifications. The APP will be relaunched.',
    PROFILE: {
      TITLE: 'Profile',
      SUBTITLE: 'Your profile',
    },
    NOTIFICATIONS: {
      TITLE: 'Notifications',
      SUBTITLE: 'Your notifications',
    },
    SECURITY: {
      TITLE: 'Security',
      SUBTITLE: 'Manage your security',
    },
    CONTACT_US: {
      TITLE: 'Contact Us',
      SUBTITLE: 'Get in touch with us',
      PHONE_NO: 'Phone number is not available',
    },
    LOGOUT: {
      BUTTON_TEXT: 'Log Out',
      SUBTITLE: 'Logout from Carelon',
    },
    VERSION: 'Version',
  },
  TERMS_OF_USE: {
    TITLE: 'Terms of Use',
    SUBTITLE: 'Read our terms of use',
  },
  PRIVACY_POLICY: {
    TITLE: 'Privacy Policy',
    SUBTITLE: 'Read our privacy policy',
    URL: 'https://confluence.elevancehealth.com/display/CBHM/Content+URLs',
  },
  CHAT: {
    TITLE: 'Chat',
    SUBTITLE: 'Chat with us',
    CHAT_HELP: 'How can I help you?',
  },
  NOTIFICATIONS: {
    TITLE: 'Notifications',
  },
  PUSH_NOTIFICATIONS_PERMISSIONS_ALERT: {
    title: 'Carelon BH App wants to send notifications.',
    message: 'Carelon BH App wants to send notifications so you can see alerts.',
    buttonNeutral: 'Ask Me Later',
    buttonNegative: 'Cancel',
    buttonPositive: 'OK',
  },
  EMPTY_STRING: '',
  MODAL_POP_UP_WINDOW: {
    TITLE: 'Password Changed',
    DESCRIPTION: 'Your account has been updated with your new password',
    RETURN_MENU: 'Return to Menu',
    RETURN_LOGIN: 'Return to Login',
    TERMS_CONDITIONS: 'Terms & Conditions',
    ACCEPT_TERMS_CONDITIONS: 'Please accept Terms & Conditions',
    CREATE_ACCOUNT_TITLE: 'Account Locked',
    CREATE_ACCOUNT_DESCRIPTION: 'User exceeded the validation limit. Sorry account is blocked!!',
    FORCE_APP_ALERT_TITLE: 'Update Required!',
    FORCE_APP_ALERT_DESCRIPTION: 'A new version of the app is available and required for use.',
    FORCE_APP_ALERT_BTN: 'Update Now',
  },
  PUSH_NOTIFICATIONS: {
    ANDROID_TITLE: 'Allow Carelon app to send you notifications?',
    ASKME_LATER: 'Ask Me Later',
    CANCEL: 'Cancel',
    OK: 'OK',
    INSTALLATION_ERROR: 'Something went wrong!',
  },
  TEXT_CONSTANTS: {
    DELETE: 'DELETE',
    REMEMBER_FLAG: 'rememberFlag',
    EMAIL_ADDRESS: 'emailAddress',
  },
  GENERAL: {
    AUTHENTICATE_USER: 'Unable to authenticate user. Please try again.',
    GENERIC_ERROR_TEXT: 'Something went wrong. Please try again after sometime',
    REGISTRATION_ERROR_TEXT: 'Error completing registration. Please try again.',
  },
  NOTIFICATION_WEB_LINK: {
    VIDEOS:
      'https://widget.crediblemind.com/carelon-mobile.html?cm_page=videos/6-ways-to-improve-your-health-and-well-being-at-work',
    PODCASTS:
      'https://widget.crediblemind.com/carelon-mobile.html?cm_page=podcasts/67-friday-fix-how-to-stay-mentally-strong-when-youre-stressed-out',
    INSIGHTS:
      'https://widget.crediblemind.com/carelon-mobile.html?cm_page=insights/moving-mindfulness-using-the-body-to-deepen-awareness-connection-and',
  },
  ERROR: {
    GENERIC_ERROR: 'Something went wrong! Please try again later',
  },
  PROVIDERS: {
    COUNSELOR_NAME: 'Counselor’s name or specialty (Optional)',
    ZIP_CODE: 'ZIP code/city/address',
    SEARCH: 'Search',
    CONNECT_LICENSED_COUNSELLOR: 'Connect with a licensed counselor',
    SELECT_COUNSELLOR: 'Select a counselor',
    CURRENT_LOCATION: 'Use My Current Location',
    KEY_WORD: 'Keyword',
    KEY_WORD_PLACEHOLDER: 'Name or speciality',
    LOCATION: 'Location',
    LOCATION_PLACEHOLDER: 'ZIP code, city, address',
    PROVIDER_FAVORITES: 'Save provider to Favorites',
    PROVIDER_TEXT: 'Select to send multiple meeting requests',
    PROVIDER_PATIENT_TEXT: 'Accepting new patients',
    PROVIDER_VIRTUAL_TEXT: 'Virtual counselor',
    PROVIDER_CONTACT_TEXT: 'Contact details',
    HOURS_OF_OPERATION: 'Hours of operation',
    SAVE_FAVORITES: 'Save provider to Favorites',
    REQUEST_APPOINTMENT_TEXT: 'Request Appointment',
    MILES: 'miles',
    PROVIDER_CONSULTATION: 'Consultation hours',
    CONSULTATION_HOURS_NOT_AVAILABLE: 'Consultation hours not available',
    YOUR_SEARCH: 'Your Search',
    LOG_IN: 'Log In',
    HOURS_NOT_AVAILABLE: 'Hours not available',
  },
  SHOW_FILTERS: {
    BUTTON_TEXT: 'Show Filters',
    ADVANCED_FILTERS: 'Advanced Filters',
    RESET_FILTERS: 'Clear Filters',
  },
};
