import { Dimensions, PixelRatio, StyleSheet } from 'react-native';

import { appColors } from '../../shared/src/context/appColors';
import { appFonts } from '../../shared/src/context/appFonts';
import { dimensionCheck, isAndroid, isIOS } from '../util/commonUtils';

const { width, height } = Dimensions.get('window');
const leftMargin = 20;

export const appStyles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
    backgroundColor: appColors.white,
    flexDirection: 'row',
  },
  viewContainer: {
    flex: 1,
  },
  screenContainer: {
    paddingLeft: 15,
    paddingTop: 15,
    paddingRight: 15,
    height: isIOS() ? '84%' : '85%',
  },
  splashParentContainer: {
    paddingHorizontal: 24,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  splashContainer: {
    height: isIOS() ? '96%' : '93%',
  },
  logoContainer: {
    flexDirection: 'row',
    height: '30%',
    width: '100%',
    justifyContent: 'center',
  },
  splashTextContainer: {
    flexDirection: 'row',
    height: '35%',
    width: '100%',
    justifyContent: 'center',
  },
  splashActionContainer: {
    flexDirection: 'column',
    height: '20%',
    width: '100%',
    justifyContent: 'center',
  },
  titleView: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'flex-start',
  },
  subtitleView: {
    flexDirection: 'row',
    marginVertical: 6,
    width: '100%',
    justifyContent: 'flex-start',
  },
  emailTextInputRow: {
    flexDirection: 'column',
    height: 86,
    width: '100%',
    justifyContent: 'flex-start',
  },
  registerSuccessVew: {
    height: '50%',
  },
  loginInputContainer: {
    height: '60%',
    paddingTop: 16,
  },
  accountRecoveryView: {
    height: '55%',
    paddingTop: 25,
  },
  resetSecretView: {
    height: '55%',
    paddingTop: 25,
  },
  inputputContainer: {
    height: '50%',
    marginTop: 25,
  },

  completeRegisterInputView: {
    flex: 1,
  },
  textInputContainer: {
    flexDirection: 'row',
    width: '95%',
    justifyContent: 'flex-start',
    height: 40,
  },
  highlight: {
    fontWeight: '700',
  },
  imageStyle: {
    height: PixelRatio.getPixelSizeForLayoutSize(135),
    width: '100%',
  },
  webviewContainer: {
    position: 'relative',
  },
  headerSecure: {
    backgroundColor: appColors.white,
    paddingTop: 0,
    marginTop: 0,
  },
  headerBottom: {
    borderBottomWidth: 1,
    borderBottomColor: appColors.purple,
  },
  headerBottomImmediate: {
    borderBottomWidth: 1,
    borderBottomColor: appColors.purple,
    marginTop: 15,
  },
  headerPublic: {
    backgroundColor: appColors.white,
    height: isIOS() ? 40 : 80,
  },
  privacyHeaderPublic: {
    backgroundColor: appColors.white,
    height: 50,
    borderBottomWidth: 1,
    borderBottomColor: appColors.purple,
  },
  headerlogo: {
    width: width * 0.3,
    height: height * 0.04,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: isAndroid() ? 5 : 0,
  },
  headerlogoView: {
    flexDirection: 'column',
    alignSelf: 'center',
    flex: 1,
    backgroundColor: appColors.white,
  },
  headerlogoSecure: {
    width: width * 0.3,
    height: height * 0.04,
    alignSelf: 'center',
    top: height * 0.01,
    resizeMode: 'contain',
  },
  headerActionButton: {
    backgroundColor: appColors.white,
    borderRadius: 20,
    alignItems: 'center',
    top: isIOS() ? (dimensionCheck() ? height * 0.032 : height * 0.01) : height * 0.02,
    width: width * 0.41,
    height: height * 0.03,
    justifyContent: 'center',
    borderColor: appColors.lightPurple,
    borderWidth: 2,
  },
  headerActionButtonText: {
    color: appColors.lightPurple,
    fontSize: 12,
    fontFamily: appFonts.regular,
  },
  backButton: {
    position: 'absolute',
    width: width * 0.06,
    height: height * 0.03,
    alignSelf: 'flex-start',
    resizeMode: 'contain',
  },
  backButtonTop: { top: height * 0.015 },
  backButtonImage: {
    width: width * 0.06,
    height: height * 0.03,
    resizeMode: 'contain',
    left: '8%',
  },
  notificationIcon: {
    right: width * 0.04,
    flex: 1,
  },
  notificationView: {
    right: width * 0.04,
    flex: 1,
    justifyContent: 'center',
  },
  notificationIconImage: {
    width: width * 0.07,
    height: height * 0.04,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: isAndroid() ? 5 : 0,
  },
  splashLogo: {
    width: 240,
    height: 100,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  title: {
    fontSize: 20,
    fontFamily: appFonts.bold,
    textAlign: 'left',
    color: appColors.mediumGray,
  },
  description: {
    fontSize: 16,
    flexDirection: 'row',
    fontFamily: appFonts.regular,
    color: appColors.mediumGray,
  },
  splashText: {
    fontFamily: appFonts.regular,
    fontSize: width * 0.06,
    fontWeight: 'normal',
    width: width * 0.6,
    justifyContent: 'center',
    color: appColors.mediumGray,
    textAlign: 'center',
    alignSelf: 'center',
  },
  textInput: {
    height: 40,
    borderColor: appColors.mediumGray,
    borderWidth: 1,
    padding: 10,
    width: '100%',
    borderRadius: 8,
    color: appColors.darkGray,
    fontFamily: appFonts.regular,
  },
  textInputError: {
    borderColor: appColors.lightRed,
  },
  errorText: {
    color: appColors.lightRed,
    fontFamily: appFonts.regular,
    fontSize: 14,
  },
  actionButton: {
    backgroundColor: appColors.lightPurple,
    borderColor: appColors.lightPurple,
    borderWidth: 2,
    borderRadius: 20,
    padding: 8,
    width: width * 0.5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  customActionButton: {
    backgroundColor: appColors.purple,
    borderColor: appColors.purple,
    borderWidth: 2,
    borderRadius: 20,
    padding: 8,
    width: width * 0.5,
    alignItems: 'center',
    alignSelf: 'center',
  },
  actionButtonSplash: {
    top: height * 0.7,
  },
  actionButtonDisabled: {
    backgroundColor: appColors.lighterPurple,
    borderColor: appColors.lighterPurple,
  },
  actionButtonAlt: {
    backgroundColor: appColors.white,
  },
  actionButtonText: {
    color: appColors.white,
    fontSize: 18,
    fontFamily: appFonts.regular,
  },
  actionButtonAltText: {
    color: appColors.purple,
    fontSize: 18,
  },
  buttonSubText: {
    fontSize: 14,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: appFonts.regular,
    color: appColors.mediumGray,
  },
  buttonSubTextSplash: {
    top: height * 0.765,
  },
  buttonSubTextNav: {
    color: appColors.lightPurple,
    fontFamily: appFonts.regular,
    fontSize: 14,
  },
  footerPrivacyPolicyStyle: {
    color: appColors.lightPurple,
    fontFamily: appFonts.regular,
    fontSize: 11,
  },
  footerContainer: {
    justifyContent: 'center',
    flexDirection: 'row',
  },
  footerText: {
    fontSize: 11,
    textAlign: 'center',
    alignSelf: 'center',
    color: appColors.darkPurple,
    fontFamily: appFonts.regular,
  },
  mainContainer: {
    backgroundColor: appColors.white,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
  subContainer: {
    marginTop: isIOS() ? 36 : dimensionCheck() ? height * 0.042 : height * 0.048,
    borderBottomWidth: 1,
    borderBottomColor: appColors.purple,
  },
  subLoginContainer: {
    marginTop: isIOS() ? 0 : height * 0.01,
    borderBottomWidth: 1,
    borderBottomColor: appColors.purple,
  },
  container: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  tabBar: {
    height: isIOS() ? (!dimensionCheck() ? 90 : 65) : 65,
    paddingHorizontal: 5,
    //paddingVertical: 10,
    verticalAlign: 'middle',
    backgroundColor: appColors.purple,
    justifyContent: 'center',
    alignItems: 'center',
    borderTopWidth: 0,
  },
  tabBarIcon: {
    width: 25,
    height: 25,
  },
  tabBarIconFocused: {
    tintColor: appColors.lightPurple,
  },
  checkViewStyle: {
    paddingTop: 20,
    paddingLeft: 5,
  },
  notificationsListHeaderStyle: {
    flexDirection: 'row',
    backgroundColor: appColors.lighter,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  notificationsListReadHeaderStyle: {
    flexDirection: 'row',
    backgroundColor: appColors.white,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  itemSeparatorStyle: {
    height: 0.6,
    width: '100%',
    backgroundColor: appColors.mediumDarkGray,
  },
  flatListParentView: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  notificationTextStyle: {
    paddingHorizontal: 10,
    borderColor: appColors.black,
    borderRadius: 2,
  },
  notificationTitleStyle: {
    fontFamily: appFonts.bold,
    fontSize: 14,
    color: appColors.mediumGray,
  },
  notificationDescStyle: {
    fontSize: 14,
    paddingTop: 4,
    color: appColors.mediumDarkGray,
    fontFamily: appFonts.regular,
  },
  notificationContentStye: {
    fontSize: 10,
    paddingTop: 4,
    color: appColors.mediumLightGray,
    fontFamily: appFonts.regular,
  },
  dotImageStyle: {
    marginTop: 5,
    height: 6,
    width: 6,
  },
  menuContainer: {
    margin: leftMargin,
    flexDirection: 'column',
    flex: 1,
  },
  menuSectionContainer: {
    borderColor: appColors.lightGray,
    marginTop: 10,
    marginBottom: 20,
    paddingHorizontal: 15,
    paddingVertical: 10,
    borderWidth: 1,
    borderRadius: 6,
    marginRight: 'auto',
    width: '100%',
  },
  menuItem: {
    display: 'flex',
    flexDirection: 'column',
  },
  menuImageItem: {
    width: 20,
    height: 20,
    justifyContent: 'flex-start',
  },
  menuDescriptionText: {
    fontSize: 14,
    fontFamily: appFonts.regular,
    color: appColors.mediumGray,
  },
  delAcctText: {
    fontSize: 14,
    fontFamily: appFonts.regular,
    color: appColors.red,
  },
  menuItemText: {
    fontSize: 20,
    textAlign: 'left',
    marginLeft: 5,
    fontFamily: appFonts.bold,
    color: appColors.mediumGray,
  },
  menuProfile: {
    height: 55,
  },
  menuNotifications: {
    height: 58,
  },
  menuContactUs: {
    height: 58,
  },
  menuSecurity: {
    height: 40,
    justifyContent: 'center',
    verticalAlign: 'middle',
  },
  chatSection: {
    display: 'flex',
    flexDirection: 'row',
    height: 28,
    backgroundColor: appColors.white,
    position: 'absolute',
    width: '100%',
    bottom: 90,
    borderTopColor: appColors.purple,
    borderTopWidth: 1,
  },
  chatButton: {
    flex: 1,
    marginLeft: 20,
    flexDirection: 'row',
    height: 28,
    alignItems: 'center',
  },
  chatText: {
    marginLeft: 10,
    textAlign: 'left',
    color: appColors.mediumDarkGray,
    fontFamily: appFonts.regular,
    fontSize: 13,
  },
  acceptTermsConditionsView: {
    height: 35,
    display: 'flex',
    flexDirection: 'row',
  },
  acceptPushView: {
    height: 35,
    display: 'flex',
    flexDirection: 'row',
  },
  acceptTermsText: {
    marginLeft: 10,
    textAlign: 'left',
    fontSize: 14,
    fontFamily: appFonts.arial,
    color: appColors.mediumGray,
  },
  switchView: {
    justifyContent: 'flex-end',
    position: 'relative',
    marginLeft: 'auto',
    marginTop: -25,
  },
  menuBackgroundView: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  publicbackButtonTop: { top: 0 },
  publicheaderlogo: {
    width: width * 0.3,
    height: height * 0.04,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  notificationsOnText: {
    justifyContent: 'flex-end',
    position: 'relative',
    marginLeft: 'auto',
    marginTop: -15,
    fontSize: 14,
    fontFamily: appFonts.regular,
  },
  receiveNotificationsText: {
    marginTop: 5,
    color: appColors.mediumGray,
    fontSize: 12,
    fontFamily: appFonts.regular,
  },
  menuSectionTitleView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  menuResetSecret: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 40,
    alignContent: 'center',
    alignItems: 'center',
  },
  rightArrowImage: {
    width: 26,
    height: 28,
    marginLeft: 'auto',
    resizeMode: 'contain',
  },
  phoneTextStyle: {
    color: appColors.purple,
    marginTop: 6,
    textAlign: 'center',
    textAlignVertical: 'center',
    fontFamily: appFonts.regular,
    fontSize: 14,
  },
  privacyTopViewStyle: {
    flex: 1,
    backgroundColor: appColors.white,
  },
  privacyScrollViewStyle: {
    marginHorizontal: 10,
  },
  eyeView: {
    justifyContent: 'center',
    right: 30,
  },
  eyeErrorView: {
    top: height * -0.04,
    marginLeft: 'auto',
    marginRight: 10,
  },
  eyeImg: {
    width: 22,
    height: 18,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  nameTextStyle: {
    color: appColors.mediumGray,
    textAlign: 'left',
    fontSize: 14,
    width: '100%',
    height: 20,
    fontFamily: appFonts.regular,
  },
  erroViewStyle: {
    paddingTop: 8,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  errorImage: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
    marginRight: 5,
  },
  publicFooter: {
    top: height * 0.95,
  },
  secureFooter: {
    top: height * 0.65,
  },
  bottomBarStyle: {
    height: 25,
    backgroundColor: appColors.purple,
  },
  tabBarlabelStyle: {
    color: appColors.white,
    fontFamily: appFonts.regular,
    fontSize: 11,
  },
  tabBarItemStyle: {
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    verticalAlign: 'middle',
  },
  tabBarIphoneItemStyle: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    verticalAlign: 'middle',
  },
  notificationBadgeStyle: {
    position: 'absolute',
    borderRadius: 12,
    backgroundColor: appColors.red,
    zIndex: 1,
    alignSelf: 'flex-end',
    height: 12,
    width: 12,
    justifyContent: 'center',
    alignItems: 'center',
    top: 4,
  },
  notificationBadgeStyle1: {
    position: 'absolute',
    borderRadius: 12,
    backgroundColor: appColors.red,
    zIndex: 1,
    alignSelf: 'flex-end',
    height: 12,
    width: 12,
    justifyContent: 'center',
    alignItems: 'center',
    top: 14,
  },
  notificationCountText: {
    fontSize: 6,
    color: appColors.white,
    fontWeight: 'bold',
  },
  keyboardScrollviewStyle: {},
  switchStyle: {
    borderColor: appColors.purple,
    borderWidth: 1,
  },
  actionButtonMenu: {
    borderColor: appColors.lightPurple,
    borderWidth: 2,
    borderRadius: 20,
    alignItems: 'center',
    alignSelf: 'center',
    padding: 8,
    width: width * 0.5,
  },
  footerMenu: {
    fontSize: 11,
    textAlign: 'center',
    alignSelf: 'center',
    top: 15,
    color: appColors.darkPurple,
    fontFamily: appFonts.regular,
  },
  textRequired: {
    color: appColors.purple,
  },
  secretEditableView: {
    height: 40,
    flexDirection: 'row',
    width: '95%',
    justifyContent: 'flex-start',
    backgroundColor: appColors.paleGray,
    borderRadius: 8,
  },
  secretEditableTextInput: {
    height: 40,
    borderColor: appColors.mediumGray,
    marginBottom: 10,
    padding: 10,
    borderRadius: 8,
    color: appColors.darkGray,
    fontFamily: appFonts.regular,
  },
  modalCenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: appColors.lightModalGray,
  },
  modalParentView: {
    backgroundColor: appColors.white,
    borderColor: appColors.black,
    borderWidth: 1,
    position: 'absolute',
    zIndex: 1,
    width: 260,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalButtonStyle: {
    backgroundColor: appColors.lightPurple,
    borderRadius: 60,
    flexGrow: 0.1,
    paddingVertical: 4,
    paddingTop: 4,
    height: 30,
    marginHorizontal: 12,
    justifyContent: 'center',
  },
  modalPopUpBtnText: {
    fontFamily: appFonts.regular,
    textAlign: 'center',
    fontSize: 14,
    color: appColors.white,
  },
  modalSubView: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  modalAccountText: {
    fontFamily: appFonts.regular,
    fontSize: 12,
    marginVertical: 12,
    textAlign: 'center',
  },
  modalTitle: {
    fontFamily: appFonts.regular,
    flex: 0.3,
    fontSize: 16,
    flexGrow: 0.4,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  webContainer: {
    marginBottom: isIOS() ? (!dimensionCheck() ? 170 : 105) : 100,
  },
  buildStyle: {
    marginTop: 30,
    fontFamily: appFonts.regular,
    color: appColors.mediumGray,
  },
});
