import { SearchProvider } from '../model/providerSearchResponse';

export const mockProviderInfo: SearchProvider = {
  providerId: 3528,
  name: { displayName: 'ZULMA RODRIGUEZ LCSW', firstName: 'ZULMA', lastName: 'RODRIGUEZ' },
  title: 'LCSW',
  providerType: 'Practitioner',
  contact: {
    address: {
      addr1: 'VIRTUAL VISITS ONLY',
      addr2: '',
      city: 'NEW YORK',
      state: 'NY',
      zip: '10119',
      location: { lat: 40.75031, lon: -73.992979 },
    },
    fax: '8887339280',
    officeEmail: 'contact@beaconhealthoptions.com',
    website: 'Not Available',
    phone: '8552276562',
  },
  workHours: [
    {
      day: 'FRI',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'MON',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'SAT',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'SUN',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'THU',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'TUE',
      hours: ['7:00 AM - 9:00 PM'],
    },
    {
      day: 'WED',
      hours: ['7:00 AM - 9:00 PM'],
    },
  ],
  languages: ['SPANISH', 'ENGLISH'],
  specialties: [
    { id: 1, name: 'ALCOHOL/CHEMICAL DEPENDENCY', sortOrder: 280 },
    { id: 5, name: 'ADDICTIONS, NON-CHEMICAL', sortOrder: 110 },
    { id: 6, name: 'ANGER MANAGEMENT', sortOrder: 360 },
    { id: 7, name: 'ANXIETY DISORDERS', sortOrder: 370 },
    { id: 12, name: 'CO-OCCURRING DISORDERS', sortOrder: 1690 },
    { id: 15, name: 'EATING DISORDERS', sortOrder: 3020 },
    { id: 20, name: 'GRIEF/BEREAVEMENT', sortOrder: 3920 },
    { id: 33, name: 'PANIC/PHOBIA', sortOrder: 6630 },
    { id: 34, name: 'POST TRAUMATIC STRESS DISORDER', sortOrder: 7270 },
    { id: 46, name: 'WOMENS ISSUES', sortOrder: 9750 },
    { id: 50, name: 'FAMILY THERAPY', sortOrder: 3410 },
    { id: 52, name: 'COGNITIVE BEHAVIORAL THERAPY', sortOrder: 1710 },
    { id: 67, name: 'BIPOLAR DISORDER', sortOrder: 750 },
    { id: 69, name: 'GROUP THERAPY', sortOrder: 3990 },
    { id: 80, name: 'CRITICAL INCIDENT STRESS DEBRIEFING', sortOrder: 2500 },
    { id: 90, name: 'BEHAVIOR MODIFICATION', sortOrder: 560 },
    { id: 93, name: 'DIALECTICAL BEHAVIORAL THERAPY', sortOrder: 2840 },
    { id: 10148, name: 'SOLUTION FOCUSED THERAPY', sortOrder: 8550 },
  ],
  ageGroups: ['Young Child (0 - 4)', 'Child (5 - 12)', 'Adolescent (13 - 17)', 'Adult (18 - 64)', 'Geriatric (65+) '],
  productType: [
    { id: 10146, name: 'EMPLOYEE ASSISTANCE PROGRAM', sortOrder: 3 },
    { id: 20000, name: 'MENTAL HEALTH / SUBSTANCE ABUSE DISORDER', sortOrder: 5 },
  ],
  telehealthTypes: { flag: true, states: ['CA', 'NY'], types: ['Telehealth Services', 'Virtual Only'] },
  handicap: 'N',
  publicTransportation: 'N',
  gender: 'F',
  ethnicity: 'HISPANIC OR LATINO',
  onlineAppointmentScheduleFlag: 1,
  accreditationsFlag: 0,
  ageRanges: [' 0 - 999 '],
  boardCertFlag: 1,
  culturalCompetenceTrainingFlag: 'Y',
  hospitalAffiliationsFlag: 0,
  npi: '1285835462',
  staffLanguages: ['ENGLISH'],
  taxid: ['870756106', '545860736'],
  taxonomyCodes: ['104100000X', '1041C0700X'],
  unVerifiedProvider: 0,
  yellowLabels: [
    { label: 'Accepting new patients', icon: 'accepting-new-patients', notAvailable: true },
    { icon: 'public-transportation', notAvailable: false },
    { icon: 'wheelchair-accessible', notAvailable: false },
    { label: 'Medicaid provider', icon: 'medicaid-provider' },
  ],
  beaconLocationId: 'F507631',
  fields: { distance: [2.6811461526390272] },
  id: 'R4dEMJIB-uHGCQA_7oEj',
  visitButton: {
    ariaLabel: '',
    href: '',
    isExternal: false,
    label: '',
    openAsSSP: false,
  },
};
