import { AppContextType } from '../context/appContext';

export function getMockAppContext(): Readonly<AppContextType> {
  return {
    immediateAssistanceContact: undefined,
    client: undefined,
    loggedIn: false,
    navigateScreen: undefined,
    wpoClientName: undefined,
    serviceProvider: { callService: jest.fn() },
    setClient: jest.fn(),
    setLoggedIn: jest.fn(),
    setNavigateScreen: jest.fn(),
    setServiceProvider: jest.fn(),
    deviceToken: '',
    memberAppointmentStatus: undefined,
    assessmentsSurveyId: undefined,
    setAssessmentsSurveyId: jest.fn(),
    navigationHandler: {
      linkTo: jest.fn(),
      registeredScreens: {},
      requestHideTabBar: jest.fn(),
    },
    notificationCount: 0,
    pushNotificationPayload: undefined,
    setDeviceToken: jest.fn(),
    setMemberAppointStatus: jest.fn(),
    setNotificationCount: jest.fn(),
    setPushNotificationPayload: jest.fn(),
    setUserProfileData: jest.fn(),
    userProfileData: undefined,
    chatConfig: undefined,
    setChatConfig: jest.fn(),
    setImmediateAssistanceContact: jest.fn(),
    genesysChat: undefined,
    setGenesysChat: jest.fn(),
    isAutoLogOut: false,
    setIsAutoLogOut: jest.fn(),
    menuData: undefined,
    setMenuData: jest.fn(),
    host: undefined,
    setHost: jest.fn(),
    setWpoClientName: jest.fn(),
    hideChat: false,
    setHideChat: jest.fn(),
    headerInfo: undefined,
    setHeaderInfo: jest.fn(),
    homeData: undefined,
    setHomeData: jest.fn(),
    metrics: {
      trackAction: jest.fn(),
      trackState: jest.fn(),
    },
  };
}
