import { FooterData } from '../models/menu';

export const footerData: FooterData[] = [
  {
    openURLInNewTab: false,
    redirectUrl: '',
    icon: 'Home.png',
    id: 'home',
    label: 'Home',
    experienceType: 'public',
    type: 'footerItem',
  },
  {
    openURLInNewTab: false,
    redirectUrl: '',
    icon: 'Material - people.png',
    id: 'memberPlan',
    label: 'Member Plan',
    experienceType: 'public',
    type: 'footerItem',
  },
  {
    openURLInNewTab: false,
    redirectUrl: '',
    icon: 'Medication.png',
    id: 'appointments',
    label: 'Appointments',
    experienceType: 'public',
    type: 'footerItem',
  },
  {
    openURLInNewTab: false,
    redirectUrl: '',
    icon: 'Mark Unread Chat_Alt.png',
    id: 'wellness',
    label: 'Wellness',
    experienceType: 'public',
    type: 'footerItem',
  },
  {
    openURLInNewTab: false,
    redirectUrl: 'accordian:data',
    data: [
      {
        openURLInNewTab: false,
        redirectUrl: 'accordian:data',
        data: [
          {
            id: 'ProviderSearch',
            label: 'Provider Search',
            openURLInNewTab: false,
            redirectUrl: 'page:providerSearch',
            type: 'menuItem.list.child',
          },
          {
            id: 'Appointments',
            label: 'Appointments',
            openURLInNewTab: false,
            redirectUrl: 'page:appointments',
            type: 'menuItem.list.child',
          },
        ],
        icon: 'calendarPlus',
        id: 'care',
        label: 'Care',
        type: 'menuItem.list',
      },
      {
        openURLInNewTab: false,
        redirectUrl: 'accordian:data',
        data: [
          {
            id: 'PlanSummary',
            label: 'Plan Summary',
            openURLInNewTab: false,
            redirectUrl: 'page:planSummary',
            type: 'menuItem.list.child',
          },
          {
            id: 'Claims',
            label: 'Claims',
            openURLInNewTab: false,
            redirectUrl: 'page:claims',
            type: 'menuItem.list.child',
          },
          {
            id: 'Authorizations',
            label: 'Authorizations',
            openURLInNewTab: false,
            redirectUrl: 'page:authorizations',
            type: 'menuItem.list.child',
          },
          {
            id: 'BenefitsAndCoverage',
            label: 'Benefits and Coverage',
            openURLInNewTab: false,
            redirectUrl: 'page:benefitsAndCoverage',
            type: 'menuItem.list.child',
          },
        ],
        icon: 'people',
        id: 'memberPlan',
        label: 'Member Plan',
        type: 'menuItem.list',
      },
      {
        icon: 'hospitalIndemnity',
        id: 'servicesAndBenefits',
        label: 'Services and Benefits',
        openURLInNewTab: false,
        redirectUrl: 'page:servicesAndBenefits',
        type: 'menuItem.list',
      },
      {
        icon: 'idVerified',
        id: 'carelonAssessments',
        label: 'Carelon Assessments',
        openURLInNewTab: false,
        redirectUrl: 'page:carelonAssessments',
        type: 'menuItem.list',
      },
      {
        icon: 'dental',
        id: 'carelonWellbeing',
        label: 'Carelon Wellbeing',
        openURLInNewTab: false,
        redirectUrl: 'page:carelonWellbeing',
        type: 'menuItem.list',
      },
      {
        icon: 'supplementalHealth',
        id: 'wellnessContent',
        label: 'Wellness Content',
        openURLInNewTab: false,
        redirectUrl: 'page:wellness',
        type: 'menuItem.list',
      },
      {
        icon: 'customerSupport',
        id: 'contactUs',
        label: 'Contact Us',
        openURLInNewTab: false,
        redirectUrl: 'page:contactUs',
        type: 'menuItem.list',
      },
      {
        openURLInNewTab: false,
        redirectUrl: 'page:networkLogger',
        environments: ['dev1', 'sit1', 'uat1'],
        icon: 'customerSupport',
        id: 'networkLogger',
        label: 'Network Logger',
        type: 'menuItem.list',
      },
      {
        openURLInNewTab: false,
        redirectUrl: 'page:changeClient',
        environments: ['dev1', 'sit1', 'uat1'],
        icon: 'customerSupport',
        id: 'changeClient',
        label: 'Change Client',
        type: 'menuItem.list',
      },
      {
        openURLInNewTab: false,
        redirectUrl: 'page:aepAssurence',
        environments: ['dev1', 'sit1', 'uat1'],
        icon: 'customerSupport',
        id: 'aepAssurence',
        label: 'AEP Assurence',
        type: 'menuItem.list',
      },
      {
        openURLInNewTab: false,
        redirectUrl: 'page:account',
        icon: 'userMaleCircle',
        id: 'account',
        label: 'Account',
        experienceType: 'secure',
        type: 'menuItem.list',
      },
      {
        id: 'signin',
        label: 'Sign In',
        openURLInNewTab: false,
        redirectUrl: 'page:signin',
        experienceType: 'public',
        type: 'menuItem.button',
        isPrimaryButton: false,
      },
      {
        id: 'createAccount',
        label: 'Create Account',
        openURLInNewTab: false,
        redirectUrl: 'page:createAccount',
        experienceType: 'public',
        type: 'menuItem.button',
        isPrimaryButton: true,
      },
      {
        id: 'logout',
        label: 'Log Out',
        openURLInNewTab: false,
        redirectUrl: 'page:logout',
        experienceType: 'secure',
        type: 'menuItem.button',
        isPrimaryButton: false,
      },
    ],
    icon: 'menu',
    id: 'menu',
    label: 'Menu',
    type: 'footerItem',
  },
];
